language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
  - NETTE=nette-2.3-dev
  - NETTE=nette-2.3

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update
  - mkdir -p vendor/bin
  - wget -O vendor/bin/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php vendor/bin/composer-nette

install:
  - travis_retry composer update --no-interaction --prefer-dist
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - travis_retry composer create-project --no-interaction kdyby/code-checker /tmp/code-checker

script:
  - vendor/bin/tester -p php -c ./tests/php.ini-unix ./tests/KdybyTests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php /tmp/code-checker/src/code-checker.php --short-arrays -d src
  - php /tmp/code-checker/src/code-checker.php --short-arrays -d tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
