language: php

env:
  - NETTE=nette-2.2-dev
  - NETTE=nette-2.2

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - composer self-update
  - composer create-project --prefer-source --dev --no-interaction jakub-onderka/php-parallel-lint vendor/jakub-onderka/php-parallel-lint
  - php vendor/jakub-onderka/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .

install:
  - mkdir -p vendor/bin
  - wget -O vendor/bin/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php vendor/bin/composer-nette
  - composer install --no-interaction --prefer-source --dev

script: vendor/bin/tester -c ./tests/php.ini-unix ./tests/KdybyTests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
